version: '2.2'
services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - default-network
volumes:
  dbdata:

networks:
  default-network:
    name: default-network