FROM ubuntu:latest

RUN apt-get update && apt-get install -y vim && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash user
USER user
WORKDIR /home/user
RUN mkdir Desktop
WORKDIR /home/user/Desktop
RUN mkdir Felipe

CMD ["bash"]